version: '3.8'

volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: mrvinil/yamdb_final:latest
    restart: always
    volumes:
      - ./static_valume:/code/static/
      - ./media_valume:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./static_valume:/code/static/
      - ./media_valume:/code/media/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

      -
    depends_on:
      - web
